### ISSUE TITLE
AppMenu not displaying any content/interactions when using paged "help"

### ISSUE THREAD

**Issue by trynfulf** [CasuallyCalm/discord-pretty-help#88]
When using the AppMenu part of pretty-help, the notification of my bot typing is sent however, no message/embed is sent with the command `~help`. Although when using a specific command help such as `~help "command"``, the interactions are sent. When using the EmojiMenu, the help command works completely fine and I am having no issues with this. I seem to remember a timer until the slash commands work, although, I do not know if this still applies. 
![The relevant code snippet](https://github.com/CasuallyCalm/discord-pretty-help/assets/76261952/9b0a4935-0b28-4694-a414-f80981deb3bf)

The below image shows the difference with the two commands with the first "~help" being the appMenu and the next being the EmojiMenu.
![image](https://github.com/CasuallyCalm/discord-pretty-help/assets/76261952/4c41b025-f53a-4913-a4c6-8178b2e307fa)

**Comment by CasuallyCalm** [comment]
I can't seem to reproduce this. Are there any errors when you try to use it?

**Comment by trynfulf** [comment]
No, it is very strange

**Comment by CasuallyCalm** [comment]
Odd. Can you provide the code you're working with or run the [test cog](https://github.com/CasuallyCalm/discord-pretty-help/tree/master/tests) and see if it still does the same thing?

**Comment by trynfulf** [comment]
[AutoChar.zip](https://github.com/CasuallyCalm/discord-pretty-help/files/11455148/AutoChar.zip)
Here is everything, only the token has been removed

**Comment by CasuallyCalm** [comment]
Got it. Looks like it was an issue with the description of the select menu being too large. Should be fixed now so reinstall and try it again.

**Comment by trynfulf** [comment]
It all works wonderfully now. Thank you very much for fixing this.
